version: "3.1"

services:

  node:
    container_name: tle728-api
    build:
      context: .
      dockerfile: ./src/dockerfiles/Dockerfile_api
    ports:
      - 12005:12005
    links:
      - db
    depends_on:
      - db

  db:
    container_name: tle728-db
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: .
      dockerfile: ./src/dockerfiles/Dockerfile_db
    environment:
      - MYSQL_DATABASE=property
      - MYSQL_USER=tle728
      - MYSQL_PASSWORD=secretPassword
      - MYSQL_ROOT_PASSWORD=eggs
    hostname: db
    volumes:
    - tle728-db-vol:/var/lib/mysql

volumes:
  tle728-db-vol: {}

