version: "3.1"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    container_name: tle728-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=eggs
    hostname: db
    ports:
      - 3307:3306
    volumes:
      - tle728-db-vol:/var/lib/mysql
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge

volumes:
  tle728-db-vol: {}
