apiVersion: v1
kind: Service
metadata:
  name: tle728-db-fixed-ip-service
  labels:
    app: cs4783-spring2021-db
spec:
  selector:
    app: cs4783-spring2021-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
