apiVersion: v1
kind: Service
metadata:
  name: tle728-api-service
  labels:
    app: cs4783-spring2021-api
spec:
  type: LoadBalancer
  selector:
    app: cs4783-spring2021-api
  ports:
  - protocol: TCP
    name: https
    port: 12005
    targetPort: 12005